__attribute((naked))
void _start(void)
{
    asm (
        ".LC0:\n"
        ".ascii	\"Hello World!\\012\\000\"\n"
        ".align	2\n"
        ".LC1:\n"
        ".ascii	\"\\012\\000\"\n"
        ".align	2\n"
        "push	{r4, r5, r6, r7, r8, r9, r10, fp, lr}\n"
        "mov	r3, #0\n"
        "ldr	r4, .L22\n"
        "mov	r10, r0\n"
        ".LPIC0:\n"
        "add	r4, pc, r4\n"
        "mov	r8, r1\n"
        ".L3:\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "add	r1, r4, r3\n"
        "rsb	r2, r3, #13\n"
        "swi     #0\n"
        "cmp	r0, #0\n"
        "add	r3, r3, r0\n"
        "ble	.L2\n"
        "cmp	r3, #12\n"
        "ble	.L3\n"
        ".L2:\n"
        "cmp	r10, #0\n"
        "pople	{r4, r5, r6, r7, r8, r9, r10, fp, pc}\n"
        "ldr	fp, .L22+4\n"
        "sub	r8, r8, #4\n"
        ".LPIC1:\n"
        "add	fp, pc, fp\n"
        "mov	r6, #0\n"
        ".L6:\n"
        "ldr	r5, [r8, #4]!\n"
        "cmp	r5, #0\n"
        "beq	.L8\n"
        "mov	r2, r5\n"
        "ldrb	r3, [r2], #1\n"
        "cmp	r3, #0\n"
        "beq	.L8\n"
        "mov	r4, #0\n"
        ".L9:\n"
        "ldrb	r3, [r2], #1\n"
        "add	r4, r4, #1\n"
        "cmp	r3, #0\n"
        "bne	.L9\n"
        "b	.L10\n"
        ".L21:\n"
        "cmp	r4, r3\n"
        "ble	.L8\n"
        ".L10:\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "add	r1, r5, r3\n"
        "sub	r2, r4, r3\n"
        "swi     #0\n"
        "cmp	r0, #0\n"
        "add	r3, r3, r0\n"
        "bgt	.L21\n"
        ".L8:\n"
        "mov	r0, #1\n"
        "mov	r7, #4\n"
        "mov	r1, fp\n"
        "mov	r2, r0\n"
        "swi     #0\n"
        "add	r6, r6, r2\n"
        "cmp	r10, r6\n"
        "bne	.L6\n"
        "pop	{r4, r5, r6, r7, r8, r9, r10, fp, pc}\n"
        ".L23:\n"
        ".align	2\n"
        ".L22:\n"
        ".word	.LC0-(.LPIC0+8)\n"
        ".word	.LC1-(.LPIC1+8)\n"
        );
};
