__attribute((naked))
void _start(void)
{
    asm (
        "_start:\n"
        "push	{r0-r12, lr}\n"
        "ldr    r0, [sp, #56]\n"
        "add    r1, sp, #60\n"
        "mov	r8, r1\n"
        "ldr	r10, .L22\n"
        "sub	sp, sp, #20\n"
        ".LPIC0:\n"
        "add	r10, pc, r10\n"
        "mov	r6, #0\n"
        "str	r0, [sp, #8]\n"
        ".L3:\n"
        "mov	r3, #0\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "add	r1, r10, r6\n"
        "rsb	r2, r6, #13\n"
        "mov	r4, r3\n"
        "mov	r5, r3\n"
        "swi #0\n"
        "cmp	r0, #0\n"
        "add	r6, r6, r0\n"
        "ble	.L2\n"
        "cmp	r6, #12\n"
        "ble	.L3\n"
        ".L2:\n"
        "ldr	r3, [sp, #8]\n"
        "cmp	r3, #0\n"
        "ble	.L1\n"
        "ldr	r3, .L22+4\n"
        "mov	fp, #0\n"
        ".LPIC1:\n"
        "add	r3, pc, r3\n"
        "str	r3, [sp, #12]\n"
        "sub	r3, r8, #4\n"
        "str	r3, [sp, #4]\n"
        ".L6:\n"
        "ldr	r3, [sp, #4]\n"
        "ldr	r10, [r3, #4]!\n"
        "cmp	r10, #0\n"
        "str	r3, [sp, #4]\n"
        "beq	.L8\n"
        "mov	r3, r10\n"
        "ldrb	r2, [r3], #1\n"
        "cmp	r2, #0\n"
        "beq	.L8\n"
        "mov	r8, #0\n"
        ".L9:\n"
        "ldrb	r6, [r3], #1\n"
        "add	r8, r8, #1\n"
        "cmp	r6, #0\n"
        "bne	.L9\n"
        "b	.L10\n"
        ".L21:\n"
        "cmp	r8, r6\n"
        "ble	.L8\n"
        ".L10:\n"
        "mov	r3, #0\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "add	r1, r10, r6\n"
        "sub	r2, r8, r6\n"
        "mov	r4, r3\n"
        "mov	r5, r3\n"
        "swi #0\n"
        "cmp	r0, #0\n"
        "add	r6, r6, r0\n"
        "bgt	.L21\n"
        ".L8:\n"
        "mov	r3, #0\n"
        "mov	r0, #1\n"
        "ldr	r1, [sp, #12]\n"
        "mov	r7, #4\n"
        "mov	r2, r0\n"
        "mov	r4, r3\n"
        "mov	r5, r3\n"
        "swi #0\n"
        "ldr	r3, [sp, #8]\n"
        "add	fp, fp, r2\n"
        "cmp	r3, fp\n"
        "bne	.L6\n"
        ".L1:\n"
        "add	sp, sp, #20\n"
        "pop	{r0-r12, lr}\n"
        "ldr     ip, .ENTRY\n"
        "bx      ip\n"
        ".align	2\n"
        ".L22:\n"
        ".word	.LC0-(.LPIC0+8)\n"
        ".word	.LC1-(.LPIC1+8)\n"
        ".align	2\n"
        ".LC0:\n"
        ".ascii	\"Hello World!\\012\\000\"\n"
        ".align	2\n"
        ".LC1:\n"
        ".ascii	\"\\012\\000\"\n"
        ".ENTRY:\n"
        ".word 0x00000000\n"
        "\n"
        );
};
