__attribute((naked))
void _start(void)
{
    asm (
        ".align	2\n"
        ".LC0:\n"
        ".ascii	\"Hello World!\\012\\000\"\n"
        ".align	2\n"
        ".LC1:\n"
        ".ascii	\"\\012\\000\"\n"
        ".text\n"
        ".align	2\n"
        "start:\n"
        "push	{r4, r5, r6, r7, r8, r9, lr}\n"
        "mov	r5, r1\n"
        "ldr	r1, .L13\n"
        "mov	r6, r0\n"
        ".LPIC0:\n"
        "add	r1, pc, r1\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "mov	r2, #13\n"
        "swi     #0\n"
        "cmp	r6, #0\n"
        "pople	{r4, r5, r6, r7, r8, r9, pc}\n"
        "ldr	r8, .L13+4\n"
        "sub	r5, r5, #4\n"
        ".LPIC1:\n"
        "add	r8, pc, r8\n"
        "mov	r4, #0\n"
        ".L5:\n"
        "ldr	r1, [r5, #4]!\n"
        "cmp	r1, #0\n"
        "moveq	r2, r1\n"
        "beq	.L3\n"
        "mov	r3, r1\n"
        "ldrb	r2, [r3], #1\n"
        "cmp	r2, #0\n"
        "beq	.L3\n"
        "mov	r2, #0\n"
        ".L4:\n"
        "ldrb	r0, [r3], #1\n"
        "add	r2, r2, #1\n"
        "cmp	r0, #0\n"
        "bne	.L4\n"
        ".L3:\n"
        "mov	r7, #4\n"
        "mov	r0, #1\n"
        "swi     #0\n"
        "mov	r0, #1\n"
        "mov	r1, r8\n"
        "mov	r2, r0\n"
        "swi     #0\n"
        "add	r4, r4, r2\n"
        "cmp	r6, r4\n"
        "bne	.L5\n"
        "pop	{r4, r5, r6, r7, r8, r9, pc}\n"
        ".L14:\n"
        ".align	2\n"
        ".L13:\n"
        ".word	.LC0-(.LPIC0+8)\n"
        ".word	.LC1-(.LPIC1+8)\n"
        );
};
