__attribute((naked))
void _start(void)
{
    asm (
        "push	{r0-r11, lr}\n"
        "ldr     r0, [sp, #52]\n"
        "add     r1, sp, #56\n"
        "mov	r6, r1\n"
        "mov	r8, r0\n"
        "mov	r7, #5\n"
        "ldr	r0, [r1]\n"
        "mov	r1, #0\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	r4, r0\n"
        "beq	.L3\n"
        "ldr	r10, .L10\n"
        "mov	r0, r1\n"
        ".LPIC0:\n"
        "add	r10, pc, r10\n"
        "mov	r7, #192\n"
        "ldr	r1, [r10]\n"
        "mov	r2, #5\n"
        "ldr	r5, [r10, #4]\n"
        "mov	r3, #2\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	r5, r0\n"
        "beq	.L3\n"
        "ldr	r3, [r10, #8]\n"
        "mov	r1, r6\n"
        "mov	r0, r8\n"
        "add	r3, r5, r3\n"
        "blx	r3\n"
        "mov	r7, #91\n"
        "ldr	r1, [r10]\n"
        "mov	r0, r5\n"
        "swi     #0\n"
        ".L3:\n"
        "mov	r7, #6\n"
        "mov	r0, r4\n"
        "swi     #0\n"
        "ldr	ip, .L10+4\n"
        ".LPIC4:\n"
        "add	ip, pc, ip\n"
        "ldr	ip, [ip, #12]\n"
        "\n"
        "pop	{r0-r11, lr}\n"
        "bx	ip\n"
        ".align	2\n"
        ".L10:\n"
        ".word	.LANCHOR0-(.LPIC0+8)\n"
        ".word	.LANCHOR0-(.LPIC4+8)\n"
        ".align	2\n"
        ".LANCHOR0:\n"
        ".word	2\n"
        ".word	1\n"
        ".word	3\n"
        ".word	4\n"
        );
};
