__attribute((naked))
void _start(void)
{
    asm (
        ".align	2\n"
        "start:\n"
        "push	{r4, r5, r6, r7, r8, r9, r10, fp, lr}\n"
        "sub	sp, sp, #20\n"
        "mov	r8, r1\n"
        "mov	fp, r0\n"
        "mov	r7, #5\n"
        "ldr	r0, [r1]\n"
        "str	r2, [sp, #12]\n"
        "mov	r1, #0\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	r4, r0\n"
        "beq	.L3\n"
        "ldr	r6, .L10\n"
        "mov	r10, r3\n"
        ".LPIC0:\n"
        "add	r6, pc, r6\n"
        "mov	r0, r1\n"
        "mov	r7, #192\n"
        "ldm	r6, {r1, r5}\n"
        "mov	r2, #7\n"
        "mov	r3, #2\n"
        "swi     #0\n"
        "cmn	r0, #1\n"
        "mov	ip, r0\n"
        "beq	.L3\n"
        "mov	r1, r8\n"
        "ldr	r8, [r6, #8]\n"
        "str	ip, [r6, #40]\n"
        "add	r8, ip, r8\n"
        "add	ip, r6, #12\n"
        "mov	r0, fp\n"
        "ldr	r2, [sp, #12]\n"
        "mov	r3, r10\n"
        "str	ip, [sp]\n"
        "blx	r8\n"
        "mov	r7, #91\n"
        "mov	r0, r8\n"
        "ldr	r1, [r6]\n"
        "swi     #0\n"
        ".L3:\n"
        "mov	r7, #6\n"
        "mov	r0, r4\n"
        "swi     #0\n"
        "add	sp, sp, #20\n"
        "pop	{r4, r5, r6, r7, r8, r9, r10, fp, pc}\n"
        ".L11:\n"
        ".align	2\n"
        ".L10:\n"
        ".word	.LANCHOR0-(.LPIC0+8)\n"
        "\n"
        ".align	2\n"
        "_thunk_start:\n"
        "push    {r0-r11, lr}\n"
        "ldr     r0, [sp, #52]\n"
        "add     r1, sp, #56\n"
        "add     r2, r1, r0, lsl #2\n"
        "mov     r3, r2\n"
        "add     r2, r2, #4\n"
        "nz:\n"
        "add     r3, r3, #4\n"
        "ldr     r4, [r3]\n"
        "cmp     r4, #0\n"
        "bne     nz\n"
        "add     r3, r3, #4\n"
        "bl      start\n"
        "pop     {r0-r11, lr}\n"
        "ldr     ip, host_entry\n"
        "bx      ip\n"
        ".align  2\n"
        "host_entry:\n"
        ".word   4\n"
        ".LANCHOR0:\n"
        "chunk_len:\n"
        ".word	2\n"
        "chunk_off:\n"
        ".word	1\n"
        "chunk_entry_off:\n"
        ".word	3\n"
        "ii:\n"
        ".word	1\n"
        ".word	5\n"
        ".word	2\n"
        ".word	6\n"
        ".word	3\n"
        ".word	7\n"
        ".word	4\n"
        ".word	8\n"
        ".word	0\n"
        ".word	9\n"
        );
};
